"""ToolRegistry — unified dispatch for Python @jarvis_tool functions + YAML skills.

Replaces the old SkillRegistry with a single registry that combines both
Python-decorated tools and YAML skill definitions, with RBAC filtering
and execution context propagation.
"""

from __future__ import annotations

import logging
import os
from typing import Any

from core.tool_result import FAILURE, make_tool_result, normalize_tool_result
from core.yaml_interpreter import YAMLInterpreter
from tools import _EXECUTION_CONTEXT, _TOOL_REGISTRY

LOGGER = logging.getLogger(__name__)

_ROLE_HIERARCHY = {
    "guest": 0,
    "member": 1,
    "resident": 1,
    "family": 2,
    "admin": 2,
    "owner": 3,
}

# Default directories to scan for YAML skills (relative to project root).
_DEFAULT_YAML_DIRS = [
    os.path.join(os.path.dirname(__file__), "..", "skills"),
    os.path.join(os.path.dirname(__file__), "..", "skills", "learned"),
]


class ToolRegistry:
    """Unified tool registry combining Python and YAML tools."""

    def __init__(
        self,
        config: dict,
        *,
        yaml_dirs: list[str] | None = None,
    ) -> None:
        """Initialize: scan YAML dirs, log tool count, warn if >15.

        Args:
            config: Application configuration dict.
            yaml_dirs: Override directories to scan for YAML skills.
                       Defaults to ``skills/`` and ``skills/learned/``.
        """
        self._config = config
        self._interpreter = YAMLInterpreter()
        self._yaml_tools: dict[str, dict[str, Any]] = {}
        self._yaml_skill_metadata: dict[str, dict[str, Any]] = {}

        dirs = yaml_dirs if yaml_dirs is not None else _DEFAULT_YAML_DIRS
        for d in dirs:
            self._scan_yaml_dir(d)

        total = self.count()
        LOGGER.info("ToolRegistry: %d tools registered", total)
        if total > 15:
            LOGGER.warning("ToolRegistry: %d tools exceed recommended limit of 15", total)

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def get_tool_definitions(self, user_role: str = "guest") -> list[dict]:
        """Return all tool definitions accessible to the given role.

        Args:
            user_role: The authenticated user's role string.

        Returns:
            A list of OpenAI-compatible tool definition dicts.
        """
        user_level = _ROLE_HIERARCHY.get(user_role.strip().lower(), 0)
        tools: list[dict] = []

        # Python tools
        for entry in _TOOL_REGISTRY.values():
            required_level = _ROLE_HIERARCHY.get(
                entry.get("required_role", "guest").strip().lower(), 0,
            )
            if user_level >= required_level:
                tools.append(entry["definition"])

        # YAML tools
        for entry in self._yaml_tools.values():
            required_level = _ROLE_HIERARCHY.get(
                entry.get("required_role", "guest").strip().lower(), 0,
            )
            if user_level >= required_level:
                tools.append(entry["definition"])

        return tools

    def get_skill_metadata(self) -> list[dict[str, Any]]:
        """Return lifecycle/exposure/classification metadata for all skills.

        This is an audit surface only. It does not affect the current LLM tool
        surface or execution behavior.
        """
        metadata: list[dict[str, Any]] = []
        for name, entry in sorted(_TOOL_REGISTRY.items()):
            metadata.append(_python_skill_metadata(name, entry))
        metadata.extend(
            self._yaml_skill_metadata[name]
            for name in sorted(self._yaml_skill_metadata)
        )
        return metadata

    def execute(
        self,
        name: str,
        args: dict,
        *,
        user_id: str | None = None,
        user_role: str = "guest",
        caller: str = "llm",
        call_id: str | None = None,
    ) -> str:
        """Execute a tool by name.

        Sets ``_EXECUTION_CONTEXT`` before calling. Dispatches to Python
        function or YAML interpreter, then normalizes every result into the
        ``jarvis.tool_result.v1`` envelope used by trace and renderers.

        Args:
            name: The tool name to execute.
            args: Input arguments dict.
            user_id: Authenticated user identifier.
            user_role: Authenticated user role.
            caller: Which route invoked the tool (llm, regex_router,
                frontend_direct, scheduler).
            call_id: Optional stable call id. Generated by the normalizer when
                omitted.

        Returns:
            A normalized JSON result string.
        """
        # Set execution context BEFORE calling the tool
        _EXECUTION_CONTEXT["user_id"] = user_id
        _EXECUTION_CONTEXT["user_role"] = user_role

        # Check Python tools first
        py_entry = _TOOL_REGISTRY.get(name)
        if py_entry is not None:
            # RBAC check
            required_level = _ROLE_HIERARCHY.get(
                py_entry.get("required_role", "guest").strip().lower(), 0,
            )
            user_level = _ROLE_HIERARCHY.get(user_role.strip().lower(), 0)
            if user_level < required_level:
                return normalize_tool_result(
                    make_tool_result(
                        FAILURE,
                        f"Permission denied: {name} requires role "
                        f"'{py_entry['required_role']}'.",
                        error_code="permission_denied",
                    ),
                    skill_name=name,
                    caller=caller,
                    call_id=call_id,
                    read_only=bool(py_entry.get("read_only", True)),
                    destructive=bool(py_entry.get("destructive", False)),
                    risk_level=_python_risk_level(py_entry),
                )
            try:
                result = py_entry["execute"](name, args, user_id=user_id, user_role=user_role)
            except Exception as exc:
                LOGGER.exception("Python tool %s failed", name)
                result = make_tool_result(
                    FAILURE,
                    f"Tool execution error: {exc}",
                    error_code="tool_execution_error",
                )
            return normalize_tool_result(
                result,
                skill_name=name,
                caller=caller,
                call_id=call_id,
                read_only=bool(py_entry.get("read_only", True)),
                destructive=bool(py_entry.get("destructive", False)),
                risk_level=_python_risk_level(py_entry),
            )

        # Check YAML tools
        yaml_entry = self._yaml_tools.get(name)
        if yaml_entry is not None:
            skill = yaml_entry["skill"]
            try:
                result = self._interpreter.execute(skill, dict(args))
            except Exception as exc:
                LOGGER.exception("YAML tool %s failed", name)
                result = make_tool_result(
                    FAILURE,
                    f"Tool execution error: {exc}",
                    error_code="tool_execution_error",
                )
            annotations = skill.get("annotations", {}) or {}
            action = skill.get("action", {}) or {}
            return normalize_tool_result(
                result,
                skill_name=name,
                caller=caller,
                call_id=call_id,
                read_only=bool(annotations.get("read_only", True)),
                destructive=bool(annotations.get("destructive", False)),
                risk_level=_yaml_risk_level(skill),
                action_type=str(action.get("type") or ""),
            )

        return normalize_tool_result(
            make_tool_result(
                FAILURE,
                f"Error: unknown tool '{name}'",
                error_code="unknown_tool",
            ),
            skill_name=name,
            caller=caller,
            call_id=call_id,
            read_only=True,
            destructive=False,
            risk_level="low",
        )

    def count(self) -> int:
        """Total registered tools (Python + YAML)."""
        return len(_TOOL_REGISTRY) + len(self._yaml_tools)

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _scan_yaml_dir(self, directory: str) -> None:
        """Scan a directory for *.yaml files and load them."""
        directory = os.path.abspath(directory)
        if not os.path.isdir(directory):
            LOGGER.debug("YAML dir does not exist, skipping: %s", directory)
            return

        for fname in sorted(os.listdir(directory)):
            if not fname.endswith(".yaml"):
                continue
            path = os.path.join(directory, fname)
            try:
                skill = self._interpreter.load_skill(path)
            except Exception:
                LOGGER.exception("Failed to load YAML skill: %s", path)
                continue

            name = skill.get("name", "")
            if not name:
                LOGGER.warning("YAML skill has no name, skipping: %s", path)
                continue

            self._yaml_skill_metadata[name] = _yaml_skill_metadata(skill, path)

            if _lifecycle_status(skill) in {"deprecated", "disabled"}:
                LOGGER.debug("Skipping unavailable YAML skill: %s", path)
                continue

            definition = self._interpreter.to_tool_definition(skill)
            required_role = skill.get("required_role", "guest")

            self._yaml_tools[name] = {
                "definition": definition,
                "skill": skill,
                "required_role": required_role,
            }
            LOGGER.debug("Loaded YAML tool: %s from %s", name, path)


def _lifecycle_status(skill: dict[str, Any]) -> str:
    lifecycle = skill.get("lifecycle")
    if isinstance(lifecycle, dict) and lifecycle.get("status"):
        return str(lifecycle["status"]).strip().lower()
    return str(skill.get("status") or "live").strip().lower()


def _yaml_risk_level(skill: dict[str, Any]) -> str:
    classification = skill.get("classification")
    if isinstance(classification, dict) and classification.get("risk_level"):
        return str(classification["risk_level"]).strip().lower()
    return str(skill.get("risk_level") or "medium").strip().lower()


def _python_risk_level(entry: dict[str, Any]) -> str:
    if "risk_level" in entry:
        return str(entry["risk_level"]).strip().lower()
    classification = entry.get("classification")
    if isinstance(classification, dict) and classification.get("risk_level"):
        return str(classification["risk_level"]).strip().lower()
    if entry.get("destructive"):
        return "medium"
    if entry.get("read_only", True):
        return "low"
    return "medium"


def _python_skill_metadata(name: str, entry: dict[str, Any]) -> dict[str, Any]:
    return {
        "name": name,
        "source": "python",
        "loaded": True,
        "required_role": entry.get("required_role", "guest"),
        "lifecycle": entry.get("lifecycle") or {},
        "exposure": entry.get("exposure") or {},
        "classification": entry.get("classification") or {},
    }


def _yaml_skill_metadata(skill: dict[str, Any], path: str) -> dict[str, Any]:
    return {
        "name": skill.get("name", ""),
        "source": "yaml",
        "path": path,
        "loaded": _lifecycle_status(skill) not in {"deprecated", "disabled"},
        "required_role": skill.get("required_role", "guest"),
        "lifecycle": _yaml_lifecycle(skill),
        "exposure": _yaml_exposure(skill),
        "classification": _yaml_classification(skill),
    }


def _yaml_lifecycle(skill: dict[str, Any]) -> dict[str, Any]:
    lifecycle = skill.get("lifecycle")
    if isinstance(lifecycle, dict):
        return lifecycle
    return {
        "status": _lifecycle_status(skill),
        "reason": "Legacy YAML skill; lifecycle not explicitly reviewed.",
        "reviewed_at": "2026-05-10",
        "phase3_action": "Review and enhance if trace shows issues.",
        "replacement": None,
    }


def _yaml_exposure(skill: dict[str, Any]) -> dict[str, Any]:
    exposure = skill.get("exposure")
    if isinstance(exposure, dict):
        return exposure
    status = _lifecycle_status(skill)
    if status == "deprecated":
        return {
            "expose_to_llm": False,
            "allow_regex": False,
            "allow_frontend_direct": False,
        }
    return {
        "expose_to_llm": True,
        "allow_regex": True,
        "allow_frontend_direct": False,
    }


def _yaml_classification(skill: dict[str, Any]) -> dict[str, Any]:
    classification = skill.get("classification")
    if isinstance(classification, dict):
        return classification

    annotations = skill.get("annotations", {}) or {}
    action = skill.get("action", {}) or {}
    atype = str(action.get("type") or "")
    read_only = bool(annotations.get("read_only", True))
    destructive = bool(annotations.get("destructive", False))

    primary = "read_only"
    risk = "low"
    if atype == "file_write":
        primary = "content_capture"
    elif atype == "zellij_send":
        primary = "delivery"
        risk = "medium"
    elif atype in {"macos_paste", "aerospace_op"}:
        primary = "local_control"
        risk = "high"
    elif not read_only:
        primary = "physical_control" if destructive else "state_changing"
        risk = "medium" if destructive else "low"

    return {
        "layer": "primitive",
        "primary": primary,
        "risk_level": risk,
        "has_side_effects": not read_only,
    }
